name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
  GHCR_REPO: ${{ secrets.GHCR_HUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  get-tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print Tags Version
        run: echo ${{ env.RELEASE_VERSION }}

  build-and-push:
    needs: get-tag-version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Prepare
        id: prep
        run: |
            IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

            # Strip git ref prefix from version
            # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            # I changed this so it takes the version from a file on my project
            VERSION=$(cat version)

            # Strip "v" prefix from tag name
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

            # Use Docker `latest` tag convention
            [ "$VERSION" == "master" ] && VERSION=latest

            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            echo ::set-output name=version::${VERSION}
            echo ::set-output name=docker_tag::${IMAGE_ID}:${VERSION}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.prep.outputs.docker_tag }}
          context: ./Docker/
          push: true

      - name: Push to Docker Hub
        if: success()
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.prep.outputs.docker_tag }}
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

    # - name: Login to GHCR
    #   if: success()
    #   uses: docker/login-action@v3
    #   with:
    #     tags: ghcr.io/${{ env.GHCR_REPO }}:${{ env.TAG }}
    #     registry: ghcr.io
    #     username: ${{ secrets.GHCR_HUB_USERNAME }}
    #     # password: x-oauth-basic
    #     password: ${{ env.GHCR_TOKEN }}
    
    # - name: Build and push
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: ./Docker/
    #       file: ./Docker/Dockerfile
    #       push: ${{ github.ref_type == 'tag' }}
    #       tags: ${{ steps.meta.outputs.tags }}
    #       labels: ${{ steps.meta.outputs.labels }}
