name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
  GHCR_REPO: ${{ secrets.GHCR_HUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./Docker/
        push: true

    - name: Push to Docker Hub
      if: success()
      uses: docker/build-push-action@v3
      with:
        tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG }}
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    # - name: Login to GHCR
    #   if: success()
    #   uses: docker/login-action@v3
    #   with:
    #     tags: ghcr.io/${{ env.GHCR_REPO }}:${{ env.TAG }}
    #     registry: ghcr.io
    #     username: ${{ secrets.GHCR_HUB_USERNAME }}
    #     # password: x-oauth-basic
    #     password: ${{ env.GHCR_TOKEN }}
    
    # - name: Build and push
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: ./Docker/
    #       file: ./Docker/Dockerfile
    #       push: ${{ github.ref_type == 'tag' }}
    #       tags: ${{ steps.meta.outputs.tags }}
    #       labels: ${{ steps.meta.outputs.labels }}
